uint8 src_index
uint8 tar_index

float32 tar_vel
float32 tar_dist

bool lv_lc_left
bool fv1_lc_left
bool fv2_lc_left

bool lv_lc_right
bool fv1_lc_right
bool fv2_lc_right

float32 lv_cur_dist
float32 fv1_cur_dist
float32 fv2_cur_dist

float32 lv_est_dist
float32 fv1_est_dist
float32 fv2_est_dist

float32 lv_r_est_dist
float32 fv1_r_est_dist
float32 fv2_r_est_dist

float32 lv_est_vel
float32 fv1_est_vel
float32 fv2_est_vel

float32 lv_r_est_vel
float32 fv1_r_est_vel
float32 fv2_r_est_vel

uint8 lv_bbox_ready
uint8 lv_r_bbox_ready

uint8 fv1_bbox_ready
uint8 fv1_r_bbox_ready

uint8 fv2_bbox_ready
uint8 fv2_r_bbox_ready

bool emergency_flag
